title: "[Decision] ..."
labels: ['Decision', 'Decision Pending']
about: "This discussion aims to arrive at a decision"

body:
  - type: dropdown
    id: status
    attributes:
      label: "Status"
      description: "Pick one of 'Decision Pending', 'Decision Resolved'"
      required: true
      options:
        - label: "Decision Pending"
        - label: "Decision Resolved"
  - type: input
    id: deadline
    attributes:
      label: "Deadline"
      description: "Deadline for providing feedback `yyyy-mm-dd`"
      required: false
  - type: input
    id: owner
    attributes:
      label: "Owner"
      description: "github handle of the decision owner"
      required: true
  - type: input
    id: scope
    attributes:
      label: "Scope"
      description: "Describe the scope, also ensure the correct labels are applied (eg. 'Analytic Domain', 'DW Tech', 'Standards', 'gsd:...')"
      required: true
  - type: input
    id: approver
    attributes:
      label: "Approver"
      description: "abcde"
      required: true
  - type: markdown
    id: problem
    attributes:
      label: "Problem"
      description: "What is the question that requires a decision?"
      required: true
      value: |
        ## What is the question that requires a decision?
        <!-- What question requires a decision? -->

        ### Context
        #### Why this problem needs to be solved?
        <!-- What happens if this decision is not made? -->

        #### Who are the stakeholders of this problem?


        ## Options

        ### Option 1: *Status*
        <!-- Pick one of "Open", "Accepted", "Rejected", "Recommended" -->

        Pros:
        - ...

        Cons:
        - ...

        ### Option 2: *Status*
        <!-- Pick one of "Open", "Accepted", "Rejected", "Recommended" -->
        etc...